openapi: "3.0.0"
info:
  title: Registry API
  version: 1.0.0
servers:
  - url: http://localhost:8100
    description: Local development server
# security:
#   - bearerAuth: []
paths:
  /ehlo:
    get:
      operationId: GetServerStatus
      summary: Health and wellness probe
      description: |-
        This endpoint can be used to check that the server is
        alive and well.
      tags:
        - Health
      responses:
        200:
          description: The server is OK.
  /api/v1/contact/{contactId}:
    put:
      operationId: UpdateContact
      summary: Update a given contact
      description: |-
        Use this endpoint to update a given contact. The
        updated contact will be returned.
      security:
        - bearerAuth: [] 
      tags:
        - Contact
      requestBody:
        description: |
          The request body contains a JSON formatted object with
          the contact details.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      parameters:
        - name: contactId
          description: |-
            The ID of the contact that is being updated.
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error 
  /api/v1/ministry:
    get:
      operationId: fetchMinistrySponsors
      summary: Fetch all ministry sponsors.
      description: |-
        Use this endpoint to fetch all of the ministry sponsors
        that are not archived.
      tags:
        - Ministry
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ministry"
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
  /api/v1/profile:
    post:
      operationId: CreateProjectProfile
      summary: Create a new project profile.
      description: |-
        Use this endpoint to create a new project profile.
      security:
        - bearerAuth: [] 
      tags:
        - Profile
      requestBody:
        description: |
          The request body contains a JSON formatted object with
          the project details.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectProfile"
      responses:
        201:
          description: The profile was created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectProfile"
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
    get:
      operationId: GetAllProjectProfiles
      summary: Fetch all project profiles.
      description: |-
        Use this endpoint to fetch all of the project profiles
        that are not archived.
      security:
        - bearerAuth: [] 
      tags:
        - Profile
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProjectProfile"
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
  /api/v1/profile/{profileId}:
    get:
      operationId: GetProjectProfile
      summary: Fetch a given project profile
      description: |-
        Use this endpoint to fetch a given project profile. The
        project profile will be returned providing it is not
        archived.
      security:
        - bearerAuth: [] 
      tags:
        - Profile
      parameters:
        - name: profileId
          description: |-
            The ID of the profile that is being requested.
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ProjectProfile"
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
    put:
      operationId: UpdateProjectProfile
      summary: Update a given project profile
      description: |-
        Use this endpoint to update a given project profile. The
        updated project profile will be returned. This endpoint
        cannot be used to update an archived project.
      security:
        - bearerAuth: [] 
      tags:
        - Profile
      parameters:
        - name: profileId
          description: |-
            The ID of the profile that is being updated.
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: The request was successful; No content returned.
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
    delete:
      operationId: DeleteProjectProfile
      summary: Delete a given project profile
      description: |-
        Use this endpoint to delete a given project profile. The
        profile is not actually delete but marked as `archived`
        and will not be returned by any other queries.
      security:
        - bearerAuth: [] 
      tags:
        - Profile
      parameters:
        - name: profileId
          description: |-
            The ID of the profile that is being deleted.
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: The request was successful; No content returned.
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
  /api/v1/profile/{profileId}/namespace:
    post:
      operationId: CreateProjectNamespace
      summary: Create a new namespace for the given project
      description: |-
        Use this endpoint to create a new namespace. The
        new namespace will be returned. This endpoint
        cannot be used to create an archived namespace.
      security:
        - bearerAuth: [] 
      tags:
        - Namespace
      parameters:
        - name: profileId
          description: |-
            The ID of the project profile that will own the namespace.
          in: path
          required: true
          schema:
            type: integer
      responses:
        201:
          description: The resource was created
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Namespace"
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
    get:
      operationId: GetProjectNamespace
      summary: Fetch the namespaces for a given profile
      description: |-
        Use this endpoint to fetch a the namespaces associated with
        the given project. The namespaces will be returned providing
        they are not archived.
      security:
        - bearerAuth: [] 
      tags:
        - Namespace
      parameters:
        - name: profileId
          description: |-
            The ID of the profile that is being queried
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Namespace"
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
  /api/v1/profile/{profileId}/namespace/{namespaceId}:
    put:
      operationId: UpdateProjectNamespace
      summary: Update a namespaces for a given profile
      description: |-
        Use this endpoint to update an existing namespaces
        associated with the given project. The namespaces will
        be returned providing it is not not archived. This endpoint
        cannot be used to archive a namespace.
      security:
        - bearerAuth: [] 
      tags:
        - Namespace
      parameters:
        - name: profileId
          description: |-
            The ID of the profile that owns the namespace
          in: path
          required: true
          schema:
            type: integer
        - name: namespaceId
          description: |-
            The ID of the namespace that is being updated
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: The request was successful; No content returned.
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
    get:
      operationId: GetAProjectNamespace
      summary: Fetch a specific namespaces for a given project profile
      description: |-
        Use this endpoint to fetch an existing namespaces
        associated with the given project. The namespaces will
        be returned providing it is not not archived.
      security:
        - bearerAuth: [] 
      tags:
        - Namespace
      parameters:
        - name: profileId
          description: |-
            The ID of the profile that owns the namespace
          in: path
          required: true
          schema:
            type: integer
        - name: namespaceId
          description: |-
            The ID of the namespace that is being retrieved
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Namespace"
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
    delete:
      operationId: DeleteAProjectNamespace
      summary: Delete a specific namespaces for a given project profile
      description: |-
        Use this endpoint to remove an existing namespaces
        associated with the given project. The namespaces will
        be marked as archived and will not be returned by any other
        endpoint or be accessible.
      security:
        - bearerAuth: [] 
      tags:
        - Namespace
      parameters:
        - name: profileId
          description: |-
            The ID of the profile that owns the namespace
          in: path
          required: true
          schema:
            type: integer
        - name: namespaceId
          description: |-
            The ID of the namespace that is being retrieved
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: The resource was removed; No content returned.
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
  /api/v1/profile/{profileId}/contacts:
    get:
      operationId: fetchProfileContacts
      summary: Fetch a given projects Product Owner and Technical Contact
      description: |-
        Use this endpoint to fetch a given projects Product Owner 
        and Technical Contact. The projects contacts will be returned 
        providing it is not archived.
      security:
        - bearerAuth: [] 
      tags:
        - Contact
      parameters:
        - name: profileId
          description: |-
            The ID of the profile that is being requested.
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Contact"
        400:
          description: The request was received but incorrect
        401:
          description: The request was received but didn't have correct access permissions
        500:
          description: Internal Error
  /api/v1/profile/{profileId}/contact-edit:
    post:
      operationId: requestContactEdit
      summary: Create a new contact edit request for the given project
      description: |-
        Use this endpoint to request an update to a projects contact details.
      security:
        - bearerAuth: [] 
      tags:
        - Contact
      parameters:
        - name: profileId
          description: |-
            The ID of the project profile that will own the namespace.
          in: path
          required: true
          schema:
            type: integer
      # TODO (sb): figure out why this fails 
      # requestBody:
      #   description: Required request body.
      #   required: true
      #   $ref: "#/components/requestBodies/ContactEditDetails"
      responses:
        204:
          description: The request was successful; No content returned.
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
  /api/v1/profile/{profileId}/quota-edit:
    get:
      operationId: fetchProfileQuotaOptions
      summary: Fetch a list of quota-edit options for given clusternamespaces
      description: |-
        Use this endpoint to fetch a list of quota-edit options
        given the project and cluster name. If cluster name is not provided,
        the default cluster will be used. A list will be returned
        providing it is not archived. A empty list will be returned if the
        project is yet to be provisioned OR there is an
        ongoing quota-edit request for this project.
      security:
        - bearerAuth: [] 
      tags:
        - QuotaEdit
      parameters:
        - name: profileId
          description: |-
            The ID of the profile that is being requested.
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                type: array
        400:
          description: The request was received but incorrect
        401:
          description: The request was received but didn't have correct access permissions
        500:
          description: Internal Error
    post:
      operationId: requestProfileQuotaEdit
      summary: Create a new namespace for the given project
      description: |-
        Use this endpoint to request new quotas for cluster namespaces
        under the given profile and cluster name. If cluster name is not provided,
        the default cluster will be used.
      security:
        - bearerAuth: [] 
      tags:
        - QuotaEdit
      parameters:
        - name: profileId
          description: |-
            The ID of the project profile that will own the namespace.
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: The request was successful; No content returned.
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
  /api/v1/profile/{profileId}/request:
    get:
      operationId: GetProjectEditRequest
      summary: Fetch a given project's edit request
      description: |-
        Use this endpoint to fetch a given project edit request. The
        edit request will be returned providing it is not archived.
      security:
        - bearerAuth: [] 
      tags:
        - Profile
      parameters:
        - name: profileId
          description: |-
            The ID of the profile that is being requested.
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/EditRequest"
        400:
          description: The request was received but incorrect
        500:
          description: Internal Error
  /api/v1/provision/sync/provisioned-profile-ids:
    get:
      operationId: getAllProvisionedProfileIds
      summary: Fetch a list of provisioned profile ids
      description: |-
        Used by bot to fetch a list of provisioned profile ids.
        The definition of provisioned for a given profile is that
        all 4 namespaces in default cluster are provisioned.
      security:
        - bearerAuth: [] 
      tags:
        - Provision
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                type: array
        500:
          description: Internal Error
  /api/v1/provision/sync/{profileId}/provisioned-profile-bot-json:
    get:
      operationId: getProvisionedProfileBotJson
      summary: Fetch a list of quota-edit options for given clusternamespaces
      description: |-
        Used by bot to fetch the JSON/NATS message for the provisioned profile
        given the profile id without any pending changes.
      security:
        - bearerAuth: [] 
      tags:
        - Provision
      parameters:
        - name: profileId
          description: |-
            The ID of the provisioned profile that is being requested.
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                type: array
        500:
          description: Internal Error
  /api/v1/provision/sync//under-pending-profile-ids:
    get:
      operationId: getAllProfileIdsUnderPending
      summary: Fetch a list of provisioned profile ids
      description: |-
        Used by bot to fetch a list of profile ids for those
        profiles that are under pending edit / create request.
      tags:
        - Provision
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                type: array
        500:
          description: Internal Error
  /api/v1/provision/sync/{profileId}/under-pending-profile-bot-json:
    get:
      operationId: getProfileBotJsonUnderPending
      summary: Fetch a list of quota-edit options for given clusternamespaces
      description: |-
        Used by bot to fetch the JSON/NATS message for the queried profile
        that is under pending edit / create request given the profile id.
        The JSON/NATS message will reflect requested changes.
      tags:
        - Provision
      parameters:
        - name: profileId
          description: |-
            The ID of profiles (currently under pending edit / create) that is being requested.
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                type: array
        500:
          description: Internal Error
components:
  schemas:
    Cluster:
      title: OCP Cluster
      description: A representation of an OCP4 (or greater) clusterId
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        description:
          type: string
        disasterRecovery:
          type: boolean
        onPrem:
          type: boolean
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
      required:
        - name
        - description
        - disasterRecovery
        - onPrem
      example:
        id: 1
        name: Calgary1
        description: BC Gov calgary data center
        disasterRecovery: true
        onPrem: true
    Namespace:
      title: Project Namespace
      description: Payload for a single project namespace
      type: object
      properties:
        id:
          type: number
        profileId:
          type: number
        clusterId:
          type: number
        archived:
          type: boolean
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
      required:
        - profileId
        - clusterId
      example:
        profileId: 11
        clusterId: 4
        archived: false
    ProjectProfile:
      title: Project Profile
      description: Payload for a project profile
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        description:
          type: string
        active:
          type: boolean
        criticalSystem:
          type: boolean
        category:
          type: string
          enum:
            - pathfinder
            - operational
        busOrgId:
          type: string
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
        notificationEmail:
          type: boolean
        notificationSMS:
          type: boolean
        notificationMSTeams:
          type: boolean
        paymentBambora:
          type: boolean
        paymentPayBC:
          type: boolean
        fileTransfer:
          type: boolean
        fileStorage:
          type: boolean
        geoMappingWeb:
          type: boolean
        geoMappingLocation:
          type: boolean
        schedulingCalendar:
          type: boolean
        schedulingAppointments:
          type: boolean
        idmSiteMinder:
          type: boolean
        idmKeyCloak:
          type: boolean
        idmActiveDir:
          type: boolean
        other:
          type: string
      required:
        - name
        - description
        - category
        - busOrgId
      example:
        name: "Health Gateway"
        description: "Helping citizen's track prescription history"
        category: "pathfinder"
        busOrgId: "HLTH"
        notificationEmail: false
        notificationSMS: false
        notificationMSTeams: false
        paymentBambora: false
        paymentPayBC: true
        fileTransfer: false
        fileStorage: false
        geoMappingWeb: false
        geoMappingLocation: false
        schedulingCalendar: true
        schedulingAppointments: false
        idmSiteMinder: false
        idmKeyCloak: false
        idmActiveDir: false
        other: "Push notifications to slack"
    Ministry:
      title: Ministry Sponsors
      description: Payload for the Ministry Sponsors
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        archived:
          type: boolean
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
      required:
        - name
      example:
        name: "Agriculture"
    Contact:
      title: Project Contacts
      description: Payload for the project contacts
      type: object
      properties:
        id:
          type: number
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        github_id:
          type: string
        role_id:
          type: number
        archived:
          type: boolean
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
      required:
        - first_name
        - last_name
        - email
        - github_id
        - role_id
      example:
        first_name: "John"
        last_name: "Doe"
        email: "john.doe@example.com"
        github_id: "johndoe1100"
        role_id: 1
    EditRequest:
      title: Edit Request
      description: Payload for an edit request
      type: object
      properties:
        id:
          type: number        
        profileId: 
          type: number
        editType:
          type: string
        editObject:
          type: string
        natsSubject:
          type: string
        natsContext:
          type: string
        archived:
          type: boolean
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
      required:
        - profileId
        - editType
        - editObject
        - natsSubject
        - natsContext
      example:
        id: 54
        profileId: 1
        editType: "contacts"
        editObject: "[{ \"id \": 233, \"firstName \": \"Jane \", \"lastName \": \"Doe \", \"email \": \"jane@example.com \", \"githubId \": \"janedoe \", \"roleId \": 1},{ \"id \": 234, \"firstName \": \"Jim \", \"lastName \": \"Doe \", \"email \": \"jim@example.com \", \"githubId \": \"jim1100 \", \"roleId \": 2}]"
        natsSubject: "registry_project_provisioning"
        natsContext: "{ \"action \": \"edit \", \"type\": \"standard \", \"profileId \": 118, \"displayName \": \"Project X \", \"namespaces \": [ { \"namespaceId \": 149, \"name \": \"4ea35c-tools \", \"clusters \": [ { \"clusterId \": 1, \"name \": \"silver \", \"provisioned \": false, \"quotas \": { \"cpu \": \"small \", \"memory \": \"small \", \"storage \": \"small \" } } ] }, { \"namespaceId \": 151, \"name \": \"4ea35c-test \", \"clusters \": [ { \"clusterId \": 1, \"name \": \"silver \", \"provisioned \": false, \"quotas \": { \"cpu \": \"small \", \"memory \": \"small \", \"storage \": \"small \" } } ] }, { \"namespaceId \": 150, \"name \": \"4ea35c-dev \", \"clusters \": [ { \"clusterId \": 1, \"name \": \"silver \", \"provisioned \": false, \"quotas \": { \"cpu \": \"small \", \"memory \": \"small \", \"storage \": \"small \" } } ] }, { \"namespaceId \": 152, \"name \": \"4ea35c-prod \", \"clusters \": [ { \"clusterId \": 1, \"name \": \"silver \", \"provisioned \": false, \"quotas \": { \"cpu \": \"small \", \"memory \": \"small \", \"storage \": \"small \" } } ] } ], \"productOwner \": { \"userId \": \"jane1100 \", \"provider \": \"github \", \"email \": \"jane.doe@example.com \" }, \"technicalContact \": { \"userId \": \"john1100 \", \"provider \": \"github \", \"email \": \"john.doe@example.com \" } }"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  # requestBodies:
  #   ContactEditDetails:
  #     description: A JSON object containing the PO and TC details
  #     required: true
  #     type: object
  #     content:
  #         application/json:
  #           schema:
  #             properties:
  #               productOwner:
  #                 $ref: "#/components/schemas/Contact"
  #               technicalContact:
  #                 $ref: "#/components/schemas/Contact"
